### ISSUE TITLE
create readme.md file for project 

### ISSUE THREAD

**Issue by peterston-e** [peterston-e/SOC-precourse-airbnb#11]
The site is a html and css clone on airbnb.co.uk so something using link and images around that

**Comment by cjstyles6** [comment]
I can help with this but i gotta know what the site is all about and you should also add a live view to the about of the repo

**Comment by peterston-e** [comment]
> I can help with this but i gotta know what the site is all about and you should also add a live view to the about of the repo

Hi sorry, thats very kind of you, but this is just a learning project for a course I'm doing. unfortunately all work has to be done myself. Im just going through the motions of creating a project. Thanks anyway

**Comment by cjstyles6** [comment]
Sure no problem but you can close the issue now that you've done them
